# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm"
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm"
      - run: npm i
      - run: npm run test

  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit

workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
